package no.nav.syfo.kafka.consumers.varselbus.domain

enum class DineSykmeldteHendelseType {
    OPPFOLGINGSPLAN_OPPRETTET,
    OPPFOLGINGSPLAN_TIL_GODKJENNING,
    DIALOGMOTE_SVAR_BEHOV,
    AKTIVITETSKRAV,
    DIALOGMOTE_INNKALLING,
    DIALOGMOTE_AVLYSNING,
    DIALOGMOTE_ENDRING,
    DIALOGMOTE_REFERAT,
}
