style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
config:
  validation: true
  warningsAsErrors: true
exceptions:
  TooGenericExceptionCaught:
    active: false
complexity:
  LongParameterList:
    active: false
  LongMethod:
    active: false
formatting:
  MaximumLineLength:
    active: false # MaxLineLength rule is already active in the detekt config
