version: '3'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=esyfovarsel
      - POSTGRES_USER=esyfovarsel-admin
      - POSTGRES_PASSWORD=password
