services:

  db:
    image: postgres:18.3-alpine3.23
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: esyfovarsel_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
