apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: esyfovarsel-job
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  schedule: "*/15 * * * *"
  vault:
    enabled: true
  env:
    - name: KTOR_ENV
      value: remote
    - name: SEND_VARSLER
      value: "JA"
    - name: DATABASE_URL
      value: jdbc:postgresql://b27dbvl024.preprod.local:5432/esyfovarsel
    - name: DATABASE_NAME
      value: esyfovarsel
    - name: DB_VAULT_MOUNT_PATH
      value: postgresql/preprod-fss
    - name: TOGGLE_MARKER_VARSLER_SOM_SENDT
      value: 'true'
    - name: TOGGLE_SEND_MERVEILEDNING_VARSLER
      value: 'true'
    - name: TOGGLE_SEND_AKTIVITETSKRAV_VARSLER
      value: 'true'