apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: esyfovarsel-job
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  schedule: "*/15 * * * *"
  env:
    - name: KTOR_ENV
      value: remote
    - name: SEND_VARSLER
      value: true