apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: esyfovarsel-job
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      rules:
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp
  schedule: "*/5 * * * *"
  filesFrom:
    - secret: esyfovarsel-serviceuser
  env:
  {{#each job}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
