apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfovarsel
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: esyfovarsel-job
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: esyfo-info-frontend
          namespace: team-esyfo
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: dokdistfordeling.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
      rules:
        - application: syfooppdfgen
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: syfosmregister
          namespace: teamsykmelding
        - application: narmesteleder
          namespace: teamsykmelding
  gcp:
    sqlInstances:
      - autoBackupHour: 1
        cascadingDelete: true
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: GCP_DB
            name: esyfovarsel
        diskAutoresize: true
        diskSize: 10
        diskType: SSD
        highAvailability: true
        insights:
          enabled: true
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        name: esyfovarsel-instance-dev
        pointInTimeRecovery: true
        tier: db-f1-micro
        type: POSTGRES_13
  ingresses:
    - "https://esyfovarsel.dev.intern.nav.no"
    - "https://esyfovarsel.intern.dev.nav.no"
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  leaderElection: true
  filesFrom:
    - secret: esyfovarsel-serviceuser
  env:
  {{#each app}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
