apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfovarsel
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 300
    timeout: 60
    periodSeconds: 10
    failureThreshold: 100
  readiness:
    path: /isReady
    initialDelay: 300
    periodSeconds: 10
    timeout: 10
  resources:
    limits:
      cpu: 4000m
      memory: 1024Mi
    requests:
      cpu: 2000m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  vault:
    enabled: true
    paths:
      - kvPath: "/serviceuser/data/prod/srvesyfovarsel"
        mountPath: "/var/run/secrets"
  azure:
    application:
      enabled: true
  webproxy: true
  ingresses:
    - "https://esyfovarsel.nais.adeo.no"
  kafka:
    pool: nav-prod
  leaderElection: true
  envFrom:
    - configmap: loginservice-idporten
  env:
  {{#each app}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
