apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: esyfovarsel-alerts
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  groups:
    - name: esyfovarsel-alerts
      rules:
        - alert: ESYFOVARSEL IS DOWN!
          expr: kube_deployment_status_replicas_available{deployment="esyfovarsel"} == 0
          for: 2m
          annotations:
            summary: "App esyfovarsel er nede i namespace {{ $labels.namespace }}"
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.namespace }}` for logger"
          labels:
            namespace: team-esyfo
            severity: critical
        - alert: HIGH RATIO OF WARNING/ERRORS IN LOG
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="esyfovarsel",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="esyfovarsel"}[3m]))) > 10
          for: 3m
          annotations:
            summary: "App esyfovarsel i namespace {{ $labels.log_namespace }} har en høy andel logging av Warning/Error"
            action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
          labels:
            namespace: team-esyfo
            severity: warning
        - alert: ESYFOVARSEL-JOB HAS FAILED
          expr: kube_job_failed{job_name=~"esyfovarsel-job.*", namespace="team-esyfo"} > 0
          for: 2m
          annotations:
            summary: "esyfovarsel-job har feilet i namespace {{ $labels.namespace }}"
            action: "Sjekk i logger hvorfor esyfovarsel-job feiler. Slett den feilede jobben med `kubectl delete job {{ $labels.job_name }}` for å stoppe denne alerten."
          labels:
            namespace: team-esyfo
            severity: warning
        - alert: KAFKA INFOTRYGD CONSUMER LAG
          expr: kafka_consumergroup_group_topic_sum_lag{topic="aap.sykepengedager.infotrygd.v1", group="esyfovarsel-group-infotrygd-01"} > 0
          for: 15m
          annotations:
            summary: "esyfovarsel har ukonsumerte Kafkameldinger på topic aap.sykepengedager.infotrygd.v1"
            action: "Finn ut hvorfor esyfovarsel har stoppet å konsumere fra topic"
          labels:
            namespace: team-esyfo
            severity: warning
        - alert: KAFKA UTBETALING CONSUMER LAG
          expr: kafka_consumergroup_group_topic_sum_lag{topic="tbd.utbetaling", group="esyfovarsel-group-utbetaling-spleis-01"} > 0
          for: 15m
          annotations:
            summary: "esyfovarsel har ukonsumerte Kafkameldinger på topic tbd.utbetaling"
            action: "Finn ut hvorfor esyfovarsel har stoppet å konsumere fra topic"
          labels:
            namespace: team-esyfo
            severity: warning



