apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: esyfovarsel-job
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      rules:
        - application: esyfovarsel
  schedule: "*/5 * * * *"
  filesFrom:
    - secret: esyfovarsel-serviceuser
  env:
    - name: KTOR_ENV
      value: remote
    - name: JOB
      value: "true"
    - name: SEND_VARSLER
      value: "true"
    - name: ESYFOVARSEL_JOB_TRIGGER_URL
      value: http://esyfovarsel/job/trigger
