apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: esyfovarsel-job
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      rules:
        - application: esyfovarsel
  schedule: "0,30 7-15 * * 1-5" # runs every 30 minutes between 07:00 and 15:00, Monday to Friday
  filesFrom:
    - secret: esyfovarsel-serviceuser
  env:
    - name: KTOR_ENV
      value: remote
    - name: JOB
      value: "true"
    - name: ESYFOVARSEL_JOB_TRIGGER_URL
      value: http://esyfovarsel/job/trigger
    - name: REVARSLE_UNREAD_AKTIVITETSKRAV
      value: "true"
