ALTER TABLE UTSENDT_VARSEL
    ADD COLUMN ansatt_fnr VARCHAR(11);

ALTER TABLE UTSENDT_VARSEL
    ADD COLUMN orgnummer VARCHAR(11);

ALTER TABLE UTSENDT_VARSEL
    ALTER COLUMN aktor_id DROP NOT NULL;
