create view UTBETALINGER
AS
select FNR, MAX_DATE FORELOPIG_BEREGNET_SLUTT, UTBET_TOM UTBETALT_TOM, GJENSTAENDE_SYKEDAGER GJENSTAENDE_SYKEDAGER
from UTBETALING_INFOTRYGD
union all
select FNR, FORELOPIG_BEREGNET_SLUTT, TOM, GJENSTAENDE_SYKEDAGER
from UTBETALING_SPLEIS