name: Build & Deploy
on: push

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/jar-app.yaml@dependabot-no-deploy
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: esyfovarsel
