name: main

on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Run tests
        run: |
          ./gradlew test
      - name: Build jar
        run: |
          ./gradlew shadowJar -x test
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        run: |
          docker build --tag ${IMAGE} .
          docker push ${IMAGE}
          echo ${IMAGE}

  deploy-dev:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy app
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-dev.yaml
          VARS: .nais/dev.json
      - name: Deploy jobb
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/send-varsler-job-dev.yaml
          VARS: .nais/dev.json

      # Notify Slack
      - name: Unsuccessful deploy notification dev
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Unsuccesful deployment - `dev` :crying_cat_face:'
          SLACK_MESSAGE: '`${{ github.event.repository.name }}` failed to deploy to dev.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: commit
          SLACK_COLOR: ${{ job.status }}

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy to NAIS Prod-fss
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy app
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/naiserator-prod.yaml
          VARS: .nais/prod.json
      - name: Deploy jobb
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/send-varsler-job-prod.yaml
          VARS: .nais/prod.json
      - name: Deploy alerts
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: .nais/alerts.yaml

      # Notify Slack
      - name: Unsuccessful deploy notification prod
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: 'Unsuccesful deployment :crying_cat_face:'
          SLACK_MESSAGE: '`${{ github.event.repository.name }}` failed to deploy to prod.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: commit
          SLACK_COLOR: ${{ job.status }}

  pling:
    if: github.ref == 'refs/heads/master'
    name: Pling!
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: Pling
        run: |
          APP=${{ github.event.repository.name }}
          AUTHOR=${{ github.event.pusher.name }}
          MESSAGE=$(echo "${{ github.event.head_commit.message }}" | tr -d '\n\r')
          curl -s -H "Content-Type: application/json" \
          -X POST \
          -d '{"app":"'"$APP"'", "author":"'"$AUTHOR"'", "message":"'"$MESSAGE"'"}' \
          https://syfoping.herokuapp.com/deploy
