name: "Deploy topic"
on:
  push:
    paths:
      - .nais/topics/**
      - .github/workflows/topic.yaml
jobs:
  deploy-topic-to-dev:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/varselbus-')
    name: Deploy topic to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy topic varselbus to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/topics/varselbus-topic.yaml
          VARS: .nais/topics/dev.json

  deploy-topic-to-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy topic to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy topic varselbus to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/topics/varselbus-topic.yaml
          VARS: .nais/topics/prod.json
